### PR TITLE
Extracting task from Mist internals

### PR DESCRIPTION
**Pull request by evertonfraga**
In Mist we download the signatures from https://4byte.directory. Here's our contribution :)

### CODE REVIEW

**Comment by ligi** [comment]
Thanks so much! :+1: :1st_place_medal: :tada: - might change the scripts to be kotlin-gradle at some point but this is a wonderful start - was not even aware of this API - will come very handy for the signer.

**Comment by evertonfraga** [comment]
Nice, glad to help!

**Comment by ligi** [comment]
@evertonfraga FYI: https://ethereum.stackexchange.com/questions/40297/should-uis-handle-4byte-signature-collisions - this is also the main reason I was going for https://github.com/ethereum-lists/4bytes/pull/2

**Comment by evertonfraga** [comment]
No problem! in our original code, it handles collisions in the data structure, but we don't make anything special at the UI level.

I liked your implementation, it prevents loading a huge object into scope. 👍

**Pull request merged**
